// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pkgilugpscinyemsbmhi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBrZ2lsdWdwc2NpbnllbXNibWhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwODk3NjgsImV4cCI6MjA2NjY2NTc2OH0.ETvfN_hvboYtjfdp93oJvdomKN5oIMjnt1YiFxZdEQM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);